### ISSUE TITLE
What is myapp

### ISSUE THREAD

**Issue by mswilson4040** [docker/docs#10299]
File: [engine/examples/dotnetcore.md](https://docs.docker.com/engine/examples/dotnetcore/)

Following the tutorial, it is not clear what `myapp` is

`docker run -d -p 8080:80 --name myapp aspnetapp`

`aspnetapp` is explained, but not `myapp`. What is `myapp`?

https://docs.docker.com/engine/examples/dotnetcore/

**Comment by emanb29** [comment]
Suggestion for copy:
https://github.com/docker/docker.github.io/blob/b59e383d16b06bd5aee5f4d14757a9e8ff5fd45d/engine/examples/dotnetcore.md#L74
becomes
`Use the following commands to build and run your Docker image (forwarding the host port 8080 to the container port 80 and giving the container the name "myapp"`


However, there are many examples of "run" being used in different examples, etc. Rather than explain each parameter to `run` at each place it's used in the documentation (and hope that they all stay current), it may be more appropriate to just assume the user will look at [the relevant section of the "run" documentation](https://docs.docker.com/engine/reference/run/#name---name).

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this as this sample will soon no longer exist in the docs.
Most of the samples have moved to https://github.com/docker/awesome-compose
You can also check out our new .net guide. The new content explains the `--name` flag.
https://docs.docker.com/language/dotnet/run-containers/#stop-start-and-name-containers
