### ISSUE TITLE
This page is confusing and not work with the latest docker as it described in the page.

### ISSUE THREAD

**Issue by rongyj** [docker/docs#10804]
File: [network/network-tutorial-host.md](https://docs.docker.com/network/network-tutorial-host/)

**Comment by thaJeztah** [comment]
Do you have more details what didn't work for you? Are you perhaps running Docker Desktop?

If so, then that could explain things not working the same (the examples were written to work on a Linux host)

We should add a note to this page about Docker Desktop (which doesn't support host mode networking, due to a different networking setup)

**Comment by rongyj** [comment]
This page seems only works for linux and it should have clear title like "Networking using the host network for Linux only". For Docker for Mac/Windows, it needs access to the VM and get this page work by following this page https://www.bretfisher.com/docker-for-mac-commands-for-getting-into-local-docker-vm/.

**Comment by rongyj** [comment]
Not only me, there are many people are confused by this page and trying to make it work in Mac/Windows.

**Comment by thaJeztah** [comment]
Let me keep the ticket open, to keep track of improving the page.

Thanks for reporting! Some of the content was written when Docker Desktop didn't exist yet, and doesn't take those setups into account, so thanks for reporting!
