### ISSUE TITLE
Compose V2 CLI installation instructions for Linux need improvement

### ISSUE THREAD

**Issue by johnwchadwick** [docker/docs#13101]
File: [compose/cli-command.md](https://docs.docker.com/compose/cli-command/)

The Compose V2 CLI installation instructions point to this script: https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh. However, after running this script, the Compose V2 CLI does not work. I filed a bug for the script not working: docker/compose-cli#1874

In order to get a proper Compose v2 setup, I instead installed Docker Edge and then manually installed the Compose V2 plugin:

```sh
mkdir -p ~/.docker/cli-plugins
curl -sSL https://github.com/docker/compose-cli/releases/download/v2.0.0-beta.4/docker-compose-linux-amd64 -o ~/.docker/cli-plugins/docker-compose
chmod +x ~/.docker/cli-plugins/docker-compose
```

The script refers to using the "manual instructions," but currently the documentation has no manual installation instructions; I suggest that manual instructions should probably be added. Since I do not know what is actually intended, lacking official sources, I have decided to write an issue instead of a pull request. I believe both the issue regarding the script not working and the documentation needing improvement are needed, even if the script is fixed.

**Comment by johnwchadwick** [comment]
> compose.v2 is a CLI plugin, just download adequate binary into your $HOME/.docker/cli-plugins directory

OK, I believe I can now confirm that this is a documentation issue. The only remaining question in my head is whether or not it's still necessary to update Docker CLI first (do not know what version of Docker CLI the plugin needs.)

**Comment by theblackhole** [comment]
The script doesn't work currently because it fetches the latest release which might not be a beta release (see [install_linux.sh#L21](https://github.com/docker/compose-cli/blob/main/scripts/install/install_linux.sh#L21)).

Instead of doing a manual install, I suggest using the current script with some changes https://github.com/docker/compose-cli/pull/1980 . This PR adds custom parameters supports like this 
```shell
curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh -s v2.0.0-beta.6
```
and still support the current usage (downloads the latest release)
```
curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
```

If this PR is merged, the doc needs to be updated with the example above (and some automation could be done to update the release tag in the docs ?)
