### ISSUE TITLE
Backslashes (to escape newline) in code boxes make code unusable

### ISSUE THREAD

**Issue by Sammeeey** [docker/docs#13136]
### Problem description

There are backslashes in several code boxes, which make it hard to use the code.
The code actually does not work if you don't delete the backslashes before (at least in Windows CMD).

### Problem location

Python Language Guide - [Use containers for development](https://docs.docker.com/language/python/develop/)
File: [ docker.github.io/language/python/develop.md ](https://github.com/docker/docker.github.io/blob/master/language/python/develop.md)

### Suggestions for a fix

[Delete backslashes and write code on one line - Pull Request](https://github.com/Sammeeey/docker.github.io/pull/3)

**Comment by thaJeztah** [comment]
Thanks for opening. Yes this is somewhat of a known issue; I don't think we should rewrite all examples to be on a single line though, as that would severely impact readability (there's many examples that are quite lengthy, and writing them on a single line will require users to scroll horizontally to see the whole command).

One solution is to duplicate all examples and have "tabs" with variations for different shells (`CMD`, `PowerShell`, `Bash` (or most POSIX shells). However, doing so will require a lot of work (in addition to making sure that all variations are properly kept "in sync").

What we _should_ do (at least short term), and something I recently discussed with @usha-mandya, is to have a page that describes all "conventions used in this documentation". That section should outline things like;

- command-line examples are written for Bash/Posix shells (unless specified otherwise)
- perhaps provide instructions on how to get such a shell on Windows machines
- for users that cannot use a POSIX shell, show how to "translate/convert" an example for their shell (e.g. how to run in CMD)

Other conventions should be outlined as well, such as:

- Use of `$` as prompt (may need to be mentioned, as common convention is to use `$` for a "non-privileged" shell, and `#` for privileged prompts, but this is easily confused for a `# comment`)
- That the documentation contains various examples that are used to _illustrate_ use of a command. Some of those may be using placeholders / values for illustrational purposes, and are not directly "runnable" (`your-org/your-image` on Docker Hub, or `<SOME_NAME>` as "placeholder")
- Probably other things


/cc @usha-mandya @StefanScherer

**Comment by Sammeeey** [comment]
Thanks for the quick reply @thaJeztah !
I think the convertions approach may be a good one and there might already be some docs where one could find similar conventions to copy?!

**Comment by thaJeztah** [comment]
yes, I think we already have "some places" where we mention conventions. It would be good to collect those into a single page, so that we can easily reference that in other places (and no need to repeat the information).

It should probably also mention things, such as

- Commonly known env-vars which may differ between environments (windows/linux/mac) or use a different syntax in those (`$PWD` vs `$(pwd)`, use of `$PATH`, `$HOME` vs `%HOMEPATH%` (+ `%HOMEDIR`), vs `~/`)
- "environment variables" (`%SOME_VAR%` vs `$SOME_VAR`), and perhaps some link to "how to set them"
- short-hand and long-hand flags (`-v` / `--volume` - shorthand flags use a single hyphen (`-`), long-hand flags use a double hyphen `--`)
- combining shorthand flags (`-i -t` is equivalent to `-it` and `-ti`) (also possible for non "boolean" flags, so perhaps needs an example for that)
- behaviour of our CLI's when repeating flags
    - flags that only accept a single value are allowed to be repeated, in which case "latter" values override "former values" (`--name=one --name=two` is equivalent to `--name=two`)
    - unlike flags that accept _multiple_ values, which can be specified multiple times, and all values are used (`--env FOO=bar --env BAR=baz`)

**Comment by usha-mandya** [comment]
Thanks @Sammeeey for flagging this. 

Agree with @thaJeztah. We need to document the conventions so our readers can easily understand the content. I've logged an internal ticket for this work item. We can keep this issue open until we fix this.
