### ISSUE TITLE
Default compose file name

### ISSUE THREAD

**Issue by tpudlik** [docker/docs#13933]
According to [compose/reference/index.md](https://docs.docker.com/compose/reference/), the default compose file name is `docker-compose.yml`.  This is stated in the `docker-compose --help` section, and reiterated further down in the document.

However, the [compose specification](https://github.com/compose-spec/compose-spec/blob/master/spec.md#compose-file) states that "The default path for a Compose file is compose.yaml (preferred) or compose.yml in working directory. Compose implementations SHOULD also support docker-compose.yaml and docker-compose.yml for backward compatibility."

This makes it a little unclear which file name should be preferred for a new project.

**Comment by danBamikiya** [comment]
Hi @tpudlik, the compose specification is a standard for the definition of multi-container platform-agnostic applications.
And multiple tools asides Docker Compose implement(use) that standard as seen here: [compose-spec#implementations](https://github.com/compose-spec/compose-spec#implementations)
![image](https://user-images.githubusercontent.com/58262528/145033368-c268ce01-8789-47f7-8807-6a03f51384d9.png)

How I understand it is that Compose spec wants  `compose.yml` to be the preferred file name across all its implementations so for docker-compose, `docker-compose.yml` will & should be the default file name but docker-compose will also support & prefer `compose.yml` file if both files exists since its spec says so:

![image](https://user-images.githubusercontent.com/58262528/145034879-43c6570f-0930-4776-913e-50de875150f6.png)


@thaJeztah ptal
