### ISSUE TITLE
Time zone is really necessary?

### ISSUE THREAD

**Issue by AI-Hunter** [docker/docs#13980]
Time zone is really necessary? I am going to build a docker file but it freeze here.

```
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Configuring tzdata
------------------

Please select the geographic area in which you live. Subsequent configuration
questions will narrow this down by presenting a list of cities, representing
the time zones in which they are located.

  1. Africa      4. Australia  7. Atlantic  10. Pacific  13. Etc
  2. America     5. Arctic     8. Europe    11. SystemV
  3. Antarctica  6. Asia       9. Indian    12. US
Geographic area: Asia


6
Tokyo
^C

```
Why you make it difficulties here? if it is necessary please give better documentation, How can I write your command for different region!!!!

please send a link, where I can learn your command!!

**Comment by thaJeztah** [comment]
This is not docker asking for the input, but the `tzdata` package on Debian and Ubuntu which, when installing, defaults to an interactive installation and asks for this input in some cases.

To force packages to be install non-interactively on Debian and Ubuntu, you can use the `DEBIAN_FRONTEND=noninteractive` environment variable. You can set this in your Dockerfile when installing the package, for example;

```dockerfile
FROM ubuntu:20.04
RUN apt-get update &&  DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
```

Or you can use a `ARG` instruction to set the environment variable; by using an `ARG` for this (instead of `ENV`) the env-var does not end up in the final image; to prevent the default behavior of `apt-get` to be changed to "non-interactively".


```dockerfile
FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y tzdata
```

**Comment by thaJeztah** [comment]
Perhaps we should describe this in https://docs.docker.com/develop/dev-best-practices/ or https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
