### ISSUE TITLE
[seccomps] - Blocked syscall table in documentation differs from actual default.json reference code 

### ISSUE THREAD

**Issue by tonkapango** [docker/docs#13984]
File: [engine/security/seccomp.md](https://docs.docker.com/engine/security/seccomp/)

The syscalls that are blocked in the "Significant syscalls blocked by the default profile" are outdated as related to the default reference provided just above the table: here: 
 https://github.com/moby/moby/blob/master/profiles/seccomp/default.json

The recommendation is to update the table to reflect the actual syscalls that are blocked.

thanks!

**Comment by thaJeztah** [comment]
Are there specific syscalls you were looking at? Note that https://github.com/moby/moby/blob/master/profiles/seccomp/default.json is the `master` branch; the current (20.10.x) release of the engine will use the profile from https://github.com/moby/moby/blob/20.10/profiles/seccomp/default.json, which may differ from that.

**Comment by tonkapango** [comment]
thanks thaJeztah.  for example, clock_adjtime is called out as blocked by default profile, yet it is allowed in default profile.  (due to the kernel code actually checking the sys_time capability before allowing time modification).

others like clone, ioperm, kcmp, etc are not "effectively blocked" but are allowed given the presence of a certain capability.   Or others, eg. personality, are allowed given certain parameter values in the call.

**Comment by thaJeztah** [comment]
Ah, yes, looks like the `clock_adjtime` sys call was added to the allow-list in https://github.com/moby/moby/pull/40929, but not updated in the docs in this repository.

> others like clone, ioperm, kcmp, etc are not "effectively blocked" but are allowed given the presence of a certain capability. Or others, eg. personality, are allowed given certain parameter values in the call.

Yes, I think the original intent was to keep the description limited to just the things that are blocked by "default", but some rules were made conditional based on kernel version or capabilities (e.g. https://github.com/moby/moby/pull/25567) to make the profile easier to use.

Perhaps it would make sense to add a section describing the "conditional" rules, and mention what capability "gates" them.


Looking at the page, some quick thoughts on other changes that could be made on that page;

- remove the note about "seccomp 2.2.1 which is not available on Ubuntu 14.04, Debian Wheezy, or Debian Jessie", because all of those distro versions are now EOL, and no longer supported by Docker Engine.
- update the "Run without the default seccomp profile" section to not use the `debian:jessy` image (EOL as mentioned)
- I think it may be good to also mention that seccomp (as well as other protection) is _disabled_ when running a container with `--privileged`
- Perhaps the page could use an example with `--security-opt seccomp=unconfined` to illustrate how to fully disable seccomp for a specific container (not recommended in general, but for completeness?)


I'm not sure I will have time to make such changes, but contributions are definitely welcome; perhaps you're interested in contributing and to open a pull request to improve the page?

**Comment by tonkapango** [comment]
hi thaJeztah. i will submit a PR next week with proposed changes.  thanks!

**Comment by thaJeztah** [comment]
Thanks in advance for contributing!! I hope my bullets / thoughts above are useful, but always open to input/suggestions 👍

**Comment by tonkapango** [comment]
include reminder in conditional syscall block table, "that best practice is to remove all capabilities except those explicitly necessary to run the processes in the container."

**Comment by neersighted** [comment]
Closing as stale; this is mostly up to date now with limited exceptions e.g. https://github.com/moby/moby/issues/45518
