### ISSUE TITLE
Missing procedures for Linux Mint

### ISSUE THREAD

**Issue by davousseau** [docker/docs#14275]
File: [engine/install/ubuntu.md](https://docs.docker.com/engine/install/ubuntu/)

I choose Ubuntu because it’s the closest to Linux Mint, but the repository cannot be found. There is no information on how to fix this. Pretty sure it is a simple error that is required to change the repository name in the link, but I don’t know which one to use.

`Err :11 https://download.docker.com/linux/ubuntu una Release
  404  Not Found [IP : 2600:9000:215f:e600:3:db06:4200:93a1 443]`

I manage to fix it using this link on this website:
[Install Docker and Docker Compose on Linux Mint 19](https://computingforgeeks.com/install-docker-and-docker-compose-on-linux-mint-19/)

Maybe you could add the missing information to the Ubuntu page since it is pretty similar to Linux Mint, or create a new page for Linux Mint.

Thanks,

David

**Comment by dbrsseau** [comment]
I saw the note after I finish installing it. I'm so sorry for the inconvenience.

**Comment by dbrsseau** [comment]
Actually, I’m not crazy. On the left side of the picture is the actual website. On the right side is the tutorial, I’m doing at the moment. The note has been removed for some reason. It should be there because it is important to know for Linux Mint users.

![Capture d’écran du 2022-02-16 15-34-28](https://user-images.githubusercontent.com/8743579/154353526-4c00d48f-ca5f-4ca0-a126-7e595c00dc7e.png)
