### ISSUE TITLE
application/vnd.docker.container.image.v1+json: No spec?

### ISSUE THREAD

**Issue by roy-work** [docker/docs#14503]
File: [registry/spec/manifest-v2-2.md](https://docs.docker.com/registry/spec/manifest-v2-2/)

According to this documentation,

> The following media types are used by the manifest formats described here, and the resources they reference:
> * […]
> * `application/vnd.docker.container.image.v1+json`: Container config JSON

I'm struggling to find any sort of specification of `application/vnd.docker.container.image.v1+json`; where might one find that?

Could the linked documentation link to the specs for the formats that aren't described in that page?

**Comment by TBBle** [comment]
As it turns out, per https://github.com/moby/moby/tree/master/image/spec, `application/vnd.docker.container.image.v1+json` is the ["v1 Image JSON" format](https://github.com/moby/moby/blob/master/image/spec/v1.2.md#image-json-description). It's also [mostly-compatible with `application/vnd.oci.image.config.v1+json`](https://github.com/opencontainers/image-spec/blob/main/media-types.md#applicationvndociimageconfigv1json), documented [here](https://github.com/opencontainers/image-spec/blob/main/config.md).
