### ISSUE TITLE
 --remove-orphans flag is not a good terminology

### ISSUE THREAD

**Issue by Hussain-Ruhullah** [docker/docs#14521]
File: [compose/reference/up.md](https://docs.docker.com/compose/reference/up/)

please change this flag to something less depressing
thanks for great work

**Comment by aevesdocker** [comment]
Thanks for your feedback. This looks like a product issue, rather than a documentation bug. Please use the following links to report Docker Desktop Community product issues:
- https://github.com/docker/for-win/issues
- https://github.com/docker/for-mac/issues
Closing this as it is not a documentation issue.
