### ISSUE TITLE
Add an example for multi-arg during the Build phase

### ISSUE THREAD

**Issue by ivan-pinatti** [docker/docs#14603]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

The multi-ARG during the Build phase was rolled out recently, however, in the page documentation there is no example of it. It would be interesting to have a section for it here; https://docs.docker.com/engine/reference/builder/#arg

**Comment by ivan-pinatti** [comment]
@anthony-o, add here the example. :)

**Comment by anthony-o** [comment]
@ivan-pinatti thanks. I tried (and was unable) to find the correct `*.md` file behind https://docs.docker.com/engine/reference/builder/#arg URL, could you point me out to the file to update please ?

**Comment by thaJeztah** [comment]
The source for that file is in the https://github.com/docker/cli repository; https://github.com/docker/cli/blob/master/docs/reference/builder.md#ARG


Contributions welcome, but if you do so make sure that the commit message has a correct DCO sign-off line, otherwise CI will fail; https://github.com/docker/cli/blob/master/CONTRIBUTING.md#sign-your-work
