### ISSUE TITLE
NTP should be avoided always in containers... unless paravirtualization is broken

### ISSUE THREAD

**Issue by otheus** [docker/docs#14834]
File: [develop/dev-best-practices.md](https://docs.docker.com/develop/dev-best-practices/)

> Always run an NTP client on the Docker host and within each container process and sync them all to the same NTP server. If you use swarm services, also ensure that each Docker node syncs its clocks to the same time source as the containers.

No. 

Userspace programs on Linux get their date-time via the system call `gettimeofday(2)`, which is usually implemented in the glibc as a VDSO call, which is like a kernel call without the context switch.  The values from that call are in turn obtained from the kernel's clock-discipline driver. In  para-virtualized kernels, this should simply delegate the information from the host -- including adjtime() run on the host. On bare-metal, either CPU registers or a timer-chip are being read for these values. 

If Docker isn't providing Linux kernels with such a paravirtualized clock discipline, get your act together and do that! Running NTP as a service within each container is incredibly wasteful and will end up producing lots of false alarms should delays result from many implementations. It also creates a networking configuration nightmare. And possibly overloading centralized NTP servers.  See notes provided by the original ntpd service: http://www.ntp.org/ntpfaq/NTP-s-algo-kernel.htm In the ideal case, NTP is simply doing network synchronization and finding that the container's clock is always correct, since those values are ultimately coming from the host.

**Comment by thaJeztah** [comment]
Hmmm, yes, that's indeed an odd recommendation; I went back looking when it was added, and looks to have been as part of this PR; https://github.com/docker/docker.github.io/pull/4312

Are you interested in contributing, and opening a pull request to remove the part about running it in containers?

**Comment by otheus** [comment]
@thaJeztah "Are you interested in contributing?" Yes/ No. Like a moth to a flame. Before I made that change, I would like someone in the docker-driver dev team to definitively answer if either (1)  the Docker daemon either is providing a device facility to pass on hardware-clock-reads or chip-timer-reads onto the host's kernel, or (2) the kernel is container-aware and has a specific driver for handling this case.

**Comment by thaJeztah** [comment]
The daemon has no specific facilities for that; containers are run by the kernel, the daemon (and OCI runtimes) only set up the container's rootfs, and namespaces, after which most things are handed over to the kernel (the daemon provides the API endpoints to interact with the container, and monitors the process, but doesn't "run" the container).

The container's process will share the clock with the host (although recent kernels (as of 5.6 / https://lore.kernel.org/lkml/158016896588.31887.14143226032971732742.tglx@nanos.tec.linutronix.de/) _do_ allow containers to run in a separate time namespace (https://man7.org/linux/man-pages/man7/time_namespaces.7.html).


I don't think that should be a reason to keep the recommendation though (but let me have a quick back-chat with others if they think otherwise)

**Comment by otheus** [comment]
@thaJeztah thanks for the general confirmation. You are thinking of the nominal case where a Linux kernel runs in a container being executed on a Linux host. What about when the host is BSD (ie, Mac) or Windows? (Not that I would do this for production). Isn't there a virtualization layer somewhere?

**Comment by thaJeztah** [comment]
> but let me have a quick back-chat with others if they think otherwise

Had a quick chat with some colleagues, and looks like we're in agreement that that (run NTP in your containers) recommendation should just be removed 👍
