### ISSUE TITLE
Insecure Registry Example is Incorrect for Buildkit

### ISSUE THREAD

**Issue by da1910** [docker/docs#15340]
File: [registry/insecure.md](https://docs.docker.com/registry/insecure/)

With buildkit you must provide "http://" in your insecure registry URL, just providing the hostname or "https://" does not work. The documentation does not make this clear, and with new(ish) versions of Docker Desktop following the documentation does not help, no useful error is raised and it leads to confusion and annoyance.

See related issue with moby and buildkit: https://github.com/moby/moby/issues/41059

**Comment by sheromon** [comment]
@da1910, I just had this same issue, and it took me a while to figure out what was wrong. I see that there were updates to the docs proposed in #11023, but they weren't merged. From the comments, it looks like they wanted to update the main example rather than adding a section under "Troubleshooting".

Do you think just updating the example under `registry/insecure.md` to include the "http://" would be good enough? It seems reasonable to me.

**Comment by da1910** [comment]
I'd be very happy with that, although it would also be worth making clear that this is intentional with a short note explaining why it's necessary.

**Comment by bennettp123** [comment]
> Do you think just updating the example under `registry/insecure.md` to include the "http://" would be good enough? It seems reasonable to me.

fwiw I don't think it works under buildkit—I'm testing it now and it's not falling back from https to http

as a workaround I'm going to try a self-signed cert—hopefully it still allows insecure http with bad certs

**Comment by jpeeler** [comment]
@bennettp123 is there a way to confirm the configuration without performing a build? In my case, it'd be ideal if the default builder could simply be reconfigured.

FWIW, [this comment ](https://github.com/docker/buildx/issues/1370#issuecomment-1308479499) is authoritative with regard in needing to configure buildkit separately.
