### ISSUE TITLE
There is no explanation of how the "filter" option works

### ISSUE THREAD

**Issue by alex-piccione** [docker/docs#15625]
File: [engine/reference/commandline/container_ls.md](https://docs.docker.com/engine/reference/commandline/container_ls/)

**Comment by LeGEC** [comment]
Unlike [engine/reference/commandline/ps](https://docs.docker.com/engine/reference/commandline/ps), which has a detailed [Filtering](https://docs.docker.com/engine/reference/commandline/ps/#filtering) section,

the docs for [`docker image ls`](https://docs.docker.com/engine/reference/commandline/image_ls/) and [`docker container ls`](https://docs.docker.com/engine/reference/commandline/container_ls/) have no description of what filters can be used (description of syntax and meaning).

Since there isn't either any description for the `-f | --filter` option in the inline help, these options are really unusable even if you have access to the intergrated help and the reference documentation.

TODO : add a documentation of possible filters for both commands `docker image ls` and `docker container ls`

**Comment by LeGEC** [comment]
What part of the code should we look at to have a description (in the docker codebase) of how filters are defined and applied, both for `container ls` and `image ls` ?
