### ISSUE TITLE
/etc/apt/keyrings does not work anymore

### ISSUE THREAD

**Issue by tomasotosolini** [docker/docs#15644]
File: [engine/install/debian.md](https://docs.docker.com/engine/install/debian/)

Please put gpg key into /etc/apt/trusted.gpg.d/

**Comment by iammattcoleman** [comment]
The use of `/etc/apt/trusted.gpg.d/` is deprecated and `/etc/apt/keyrings/` is the correct approach for modern Debian-based distributions. Doing it this way avoids global installation of keyrings, only using them for the repositories that are signed by them. This approach has been supported since Debian 9 and Ubuntu 16.04.

From [the Debian wiki](https://wiki.debian.org/DebianRepository/UseThirdParty):
> The key MUST NOT be placed in /etc/apt/trusted.gpg.d or loaded by apt-key add.

What led you to conclude that `/etc/apt/keyrings/` is no longer working?
