### ISSUE TITLE
Invalid Dockerfile

### ISSUE THREAD

**Issue by BusHero** [docker/docs#15845]
The Dockerfile used in the section "Custom build outputs" is invalid.

The following scenario fails
**GIVEN** I'm using the following Dockerfile
```Dockerfile
FROM golang AS build-stage
RUN go get -u github.com/LK4D4/vndr

FROM scratch AS export-stage
COPY --from=build-stage /go/bin/vndr /
```
**WHEN** I'm running `docker build -o out .`
**THEN** my docker container builds successfully

The following error is generated:
```bash
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

File: [engine/reference/commandline/build.md](https://docs.docker.com/engine/reference/commandline/build/)

**Comment by ChandanChainani** [comment]
@BusHero The issue related to the golang since go 1.17 `go get` has been deprecated has we can also see from the error message and the other error message is related to missing `go.mod` file which is used in latest version to manage go packages.

To solve the issue either use go version below 1.17 or change this cmd `go get -u github.com/LK4D4/vndr` with [`go install`](https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies) cmd
