### ISSUE TITLE
Additional property apache2 is not allowed error

### ISSUE THREAD

**Issue by NoorSabah18** [docker/docs#16129]
while creating docker-compose.yml file i ran into the following error -> (root) Additional property apache2 is not allowed

below is my docker-compose.yml file
mysql:
  image: mysql:5.7
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD:
  volumes:
    - ../../databases/mysql:/var/lib/mysql
  container_name: mysql_service
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - 8080:80
  links:
    - mysql
  environment:
    PMA_HOST: mysql
    PMA_PORT: 3306
  container_name: phpmyadmin_service
apache2:
  image: magento2-apache2:2.0
  ports:
    - 80:80
    - 10000:10000
    - 443:443
  links:
    - mysql
  volumes:
    - C:\Users\Documents\developer\sources:/var/www/html
  container_name: apache2_service

any help or advice please

**Comment by craig-osterhout** [comment]
Hi @NoorSabah18, thanks for sharing the issue.
Since it's not formatted as code, we can't see the indentation. I suggest double check your indentation. To get more support and troubleshooting, please try the community Slack, https://join.slack.com/t/dockercommunity/shared_invite/zt-1hl072yfr-ADKgaYgcv3AUTzd9BWtkwA

If there's an issue in one of the topics of the docs, please provide more details about which topic.
