### ISSUE TITLE
Guide not compatible with latest Apple HW and/or OS Ventura

### ISSUE THREAD

**Issue by q-pablo** [docker/docs#16163]
File: [get-started/04_sharing_app.md](https://docs.docker.com/get-started/04_sharing_app/)

There's something strange when I  "Play with Docker" using an image created in a macbook pro M2 2022, Ventura 13.0.1
The first error I got was "WARNING: The requested image's platform (linux/amd64/v8) does not match the detected host platform (linux/arm64)." I closed the session and then tried adding the command --platform linux/arm64 to see if that would download the image for the host platform but it started complaining about the space left on device. 

I closed the session and tried again, but the error continues to be "no space left on device"

![Screenshot 2022-11-15 at 13 21 01](https://user-images.githubusercontent.com/118274217/201918488-fff384c7-9d90-41ab-8150-5ab9bf497545.png)

Now it doesn't matter what command I use, this is the error I see.

the commands I used:
docker run -dp 3000:3000 qpablo/getting-startd
docker run -dp 3000:3000 qpablo/getting-startd --platform linux/amd64

**Comment by q-pablo** [comment]
Managed to reproduce the original issue:

![Screenshot 2022-11-15 at 13 33 08](https://user-images.githubusercontent.com/118274217/201920628-6f88bccc-8a7d-40ec-9398-1bd538b0e4d2.png)

**Comment by thisisnimish3** [comment]
@craig-osterhout this issue is not yet solved with commit #16092 .
Are you going to fix it?

Will you be able to write the workaround here?
I think it requires us to increase the temporary memory provider to docker.

**Comment by craig-osterhout** [comment]
Hi @thisisnimish3, 
For the `no space on device` errors, you will need to try again later as Play with Docker has capacity limitations because it is a free service hosted by the community. Alternatively, you can skip that section. I can add a note to the topic to let users know the limitations. If you have any other ideas on how to demonstrate sharing images without using Play with Docker, please let us know.
