### ISSUE TITLE
external.name syntax in version 3.5 conflicts with guidance about docker links

### ISSUE THREAD

**Issue by kmanwar89** [docker/docs#16363]
File: [[compose/index.md](https://docs.docker.com/compose/compose-file/compose-file-v3/#external-1)]

While attempting to deploy [authentik](https://goauthentik.io/docs/installation/docker-compose), I was prompted that the _external.name_ syntax is deprecated as of version 3.5. The default compose file provided by authentik uses version 3.4. The docker documentation states:

`The --link flag is a legacy feature of Docker. It may eventually be removed. Unless you absolutely need to continue using it, we recommend that you use [user-defined networks](https://docs.docker.com/compose/networking/) to facilitate communication between two containers instead of using --link.`

However, I am not able to get authentik working correctly unless a `link` is placed to the `redis` and `postgresql` containers. I have tested multiple iterations of this issue and can reliably/consistently replicate it across multiple machines. The default authentik container, with no custom network, works without issue. I cannot reliably get it working unless the 'links' functionality is accompanied with the custom network stanza.

I have several logs and other files I can share as requested, but wanted to raise the initial issue and see what other questions may remain.

**Comment by glours** [comment]
Hello @kmanwar89 

Since Compose was rewritten in Golang (a.k.a Compose v2) the `version` attribut isn't need anymore as the Compose file format is now the [Compose Specification](https://github.com/compose-spec/compose-spec/blob/master/spec.md).
Good new for you, [the `links` attribute](https://github.com/compose-spec/compose-spec/blob/master/spec.md#links) isn't marked as deprecated (it was only for Swarm and v3 file format).
So you can use it safely, btw there is other way to manage the startup order of you container, maybe using `depends_on` attribut will be a better option in you case, [here the link](https://docs.docker.com/compose/startup-order/) to the doc page about this topic

FYI, this is the documentation repository, this kind of issue should be open in the [docker/compose](https://github.com/docker/compose/) repository directly 😉

**Comment by kmanwar89** [comment]
> Hello @kmanwar89
> 
> Since Compose was rewritten in Golang (a.k.a Compose v2) the `version` attribut isn't need anymore as the Compose file format is now the [Compose Specification](https://github.com/compose-spec/compose-spec/blob/master/spec.md). Good new for you, [the `links` attribute](https://github.com/compose-spec/compose-spec/blob/master/spec.md#links) isn't marked as deprecated (it was only for Swarm and v3 file format). So you can use it safely, btw there is other way to manage the startup order of you container, maybe using `depends_on` attribut will be a better option in you case, [here the link](https://docs.docker.com/compose/startup-order/) to the doc page about this topic
> 
> FYI, this is the documentation repository, this kind of issue should be open in the [docker/compose](https://github.com/docker/compose/) repository directly 😉

Thank you for this information, and I'm totally in agreement with closing this issue.

What I discovered after multiple testing was that authentik was attempting to access the same `redis` container as another service (NetBox), which because it didn't have the appropriate users created would create a failure scenario.

My workaround was to change the order in which I bring up the containers, and ensure the service names are unique.  I think the `links` feature *could* be another workaround but, as you stated, the `depends_on` attribute may be more appropriate.
