### ISSUE TITLE
Provide little information onto types of docker volume

### ISSUE THREAD

**Issue by NitishKumar06** [docker/docs#16417]
In the following link(https://docs.docker.com/get-started/06_bind_mounts/#quick-volume-type-comparisons) to understand the difference between **named volume** and **bind mounts** there is an incomplete explanation of the point _Mount example (using -v)_. 

Is `/path/to/data` representing the path where the data is stored inside the container or the path where data would be stored on the host machine? 

Please fix this.

**Comment by dvdksn** [comment]
Hi, I've just [changed this](https://github.com/docker/docs/commit/21816afcc2d54d816e08d287ba2fbdcabfffdc5f#diff-4f2b5e5809c73afd66e1599a2f8f24b1c483cf4420ec62daec989eeedc327a8cR34) to use the `--mount` flag as an example instead of `-v`, which makes it more explicit with `src` and `target` parameters. I've also added another section to illustrate how bind mounts work conceptually. I hope these changes clears any confusion.

**Comment by NitishKumar06** [comment]
@dvdksn Can you share the PR link here?

**Comment by dvdksn** [comment]
This was the PR https://github.com/docker/docs/pull/16344

**Comment by craig-osterhout** [comment]
This appears to have been resolved by the PR above. If the issue still persists, please let us know.
