### ISSUE TITLE
404 at /go/guides/ESC

### ISSUE THREAD

**Issue by enchhuang** [docker/docs#16464]
I found a broken link : https://docs.docker.com/go/guides/ESC

**Comment by jerae-duffin** [comment]
@enchhuang Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by thaJeztah** [comment]
This probably relates to https://github.com/docker/cli/pull/3973, and likely because in some cases copy/pasting from the command-line output could result in extra characters to be copied.

@enchhuang the correct URL you're looking for is https://docs.docker.com/go/guides/ (without the `ESC` at the end).


I'll close this ticket, as this is not something that can be fixed in the doc.docker.com website itself, but https://github.com/docker/cli/pull/3973 should (hopefully) help preventing this.

Thanks for reporting the issue, @enchhuang - feel free to continue the conversation after I closed the ticket 👍
