### ISSUE TITLE
couldn't signin, nor would I get the appropriate docker-desktop either for my system requirement, can't get it, like things are not going well with my projects. Can't get it.404 at /signin

### ISSUE THREAD

**Issue by bwroline** [docker/docs#16760]
I found a broken link : https://docs.docker.com/signin

**Comment by craig-osterhout** [comment]
Hi @bwroline, thanks for sharing the issue. Where did you find that link so that we can fix it?

There are a few ways to sign in, depending on your point of access:

- To sign in via Docker Desktop, please see https://docs.docker.com/desktop/get-started/#sign-in-to-docker-desktop
- To sign in via Hub, please see https://docs.docker.com/docker-id/#log-in
- To sign in via CLI, please see https://docs.docker.com/engine/reference/commandline/login/

If Docker Desktop is not available for your Linux platform, you can try requesting support for your platform here, https://github.com/docker/desktop-linux/issues

If you're new to Docker and on a supported platform, I highly recommend the getting started guide to cover the basics, https://docs.docker.com/get-started/
