### ISSUE TITLE
404 at /compose/wordpress/

### ISSUE THREAD

**Issue by SaliBasri** [docker/docs#16955]
I found a broken link : https://docs.docker.com/compose/wordpress/

- relates to https://github.com/docker/docs/pull/16001

**Comment by SashankMeka1** [comment]
I can take care of this issue, if possible?

**Comment by thaJeztah** [comment]
Sure! To fix this, we probably need to redirect it to https://docs.docker.com/samples/wordpress/

To do so, this file needs to be updated; https://github.com/docker/docs/blame/110c47743086939a9381486022a421738f14aca1/samples/wordpress.md?plain=1#L4

And a `redirect_from:` section added, so that it looks like;

```markdown
---
title: WordPress samples
description: Docker samples for WordPress.
service: wordpress
redirect_from:
  - /compose/wordpress/
---
```

**Comment by SashankMeka1** [comment]
Alright, I have created the PR!
