### ISSUE TITLE
404 at /docker-for-windows/)

### ISSUE THREAD

**Issue by skchinna7** [docker/docs#17138]
I found a broken link : https://docs.docker.com/docker-for-windows/)
I arrived on this page through: https://www.youtube.com/

I created this issue one more time. I have tried every step online and chatgpt process still docker is not working on windows. can anyone answer this question and solve this Issue. please I will follow and do anything as you say

**Comment by usha-mandya** [comment]
@skchinna7  Thanks for reporting the broken link issue. The URL you need is https://docs.docker.com/desktop/install/windows-install/.

The source file for this issue isn't located in the Docs GitHub repository. Get in touch with the maintainers of the source files to fix the broken link. I'm closing the issue here for this reason. Feel free to continue the conversation after I close.
