### ISSUE TITLE
Conflicting info on configuring HTTP/HTTPS proxies

### ISSUE THREAD

**Issue by paddy-hack** [docker/docs#17880]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The page states that as of Docker 23.0 you can set HTTP/HTTPS proxies in the `daemon.json` file.  Right after that though, the page continues with

> If you are behind an HTTP or HTTPS proxy server, for example in corporate settings, the daemon proxy configurations must be specified in the systemd service file, not in the `daemon.json` file or using environment variables.

This is contradictory and confusing at best.

### Location

https://docs.docker.com/config/daemon/systemd/

### Suggestion

I suggest replacing the text quoted above gets replaced by

> Alternatively, proxy settings can be configured via environment variables in the systemd service file.

Also, I suggest moving the `daemon.json` configuration method to the top of the section and only start talking about environment variables and how to tweak `systemd` after that.

**Comment by jojoob** [comment]
I just stumbled across the conflict in documentation as well and wanted to create an issue for it before I found this one.

The documentation under [Configure the Docker daemon to use a proxy server](https://docs.docker.com/config/daemon/systemd/#httphttps-proxy) states that

> In Docker Engine version 23.0 and later versions, **you may also configure proxy behavior for the daemon in the [daemon.json file](https://docs.docker.com/config/daemon/#configure-the-docker-daemon)**:

But later:

> If you're behind an HTTP or HTTPS proxy server, for example in corporate settings, the daemon proxy configurations must be specified in the systemd service file, **not in the daemon.json file or using environment variables**.

And [Docker daemon configuration overview](https://docs.docker.com/config/daemon/#configure-the-docker-daemon) says:

> You can configure most daemon options using the daemon.json file. **One thing you can't configure using daemon.json mechanism is an HTTP proxy.** For instructions on using a proxy, see [Configure Docker to use a proxy server](https://docs.docker.com/network/proxy/).

And the page for [docker daemon CLI](https://docs.docker.com/engine/reference/commandline/dockerd/#proxy-configuration) says again that it is possible to the configuration in three different ways...

> If you are behind an HTTP proxy server, for example in corporate settings, you may have to configure the Docker daemon to use the proxy server for operations such as pulling and pushing images. The daemon can be configured in three ways:
> 
> 1. Using environment variables (HTTP_PROXY, HTTPS_PROXY, and NO_PROXY).
> 2. Using the "http-proxy", "https-proxy", and "no-proxy" fields in the [daemon configuration file](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file) (Docker Engine 23.0 or newer).
> 3. Using the --http-proxy, --https-proxy, and --no-proxy command-line options. (Docker Engine 23.0 or newer).

Another oddity is that the damon.json example shows that the actual flag names are wrapped into a `proxies` object while states before:

> This file uses the same flag names as keys, [...]

```json
  "proxies": {
    "http-proxy": "http://proxy.example.com:80",
    "https-proxy": "https://proxy.example.com:443",
    "no-proxy": "*.test.example.com,.example.org",
  },
```

**Another chapter:** cross referencing proxy configuration for docker client...
To inject proxy configuration into containers there is another configuration for the docker client to be made in addition: https://docs.docker.com/network/proxy/
This is totally clear to me and the page even links to the daemon configuration for those who are looking for that. But a link vice versa from the proxy daemon configuration back to the docker client configuration would be nice too.

**Comment by jojoob** [comment]
I just tested two of the three methods. Setting proxy configuration via daemon.json and via environment variables (via systemd). **Both methods work and seem to have the same effect!**

Therefore I propose the removal of the paragraphs from:

1. [Configure the Docker daemon to use a proxy server](https://docs.docker.com/config/daemon/systemd/#httphttps-proxy):  
    > If you're behind an HTTP or HTTPS proxy server, for example in corporate settings, the daemon proxy configurations must be specified in the systemd service file, not in the daemon.json file or using environment variables.

2. [Docker daemon configuration overview](https://docs.docker.com/config/daemon/#configure-the-docker-daemon):  
    > You can configure most daemon options using the daemon.json file. One thing you can't configure using daemon.json mechanism is an HTTP proxy. For instructions on using a proxy, see [Configure Docker to use a proxy server](https://docs.docker.com/network/proxy/).

**Comment by thaJeztah** [comment]
Hm, thanks for reporting, yes this looks to have slipped review in https://github.com/docker/docs/pull/13786, which I originally opened in draft, but was later carried/updated by @dvdksn when we introduced support for this in the `daemon.json`. Not sure where the "must be specified in the systemd service file, not in the daemon.json" part originated from, but perhaps this was because Docker 20.10 was not yet EOL at the time,

The `daemon.json` and command-line options (flags) were added to allow configuring the daemon in a single file, without having to set _some_ options in the `daemon.json` and other options through other ways (e.g. through systemd units), and to provide an easier way to configure these options for native Windows daemons (where configuring environment-variables can be somewhat more involved).

The `daemon.json`, daemon command-line flags, and env-var (which can be specified in a systemd unit / override) can all be used;

- if both env-vars and `daemon.json` or command-line option(s) (flags) are used, then the `daemon.json` or command-line options take precedence (will override env-vars)
- using _both_ `daemon.json` _AND_ command-line options (flags) will produce an error at daemon startup (and will make the daemon refuse to start up).

In general, we recommend using the `daemon.json` configuration file for this, as it allows you to keep your configuration central to a single file, and because these settings also apply when running the daemon without the use of systemd, but in some settings it may be more common to use systemd to configure services (which could be through tools provisioning new machines), and the environment variables can be useful when running the daemon "docker-in-docker" (in which case the environment variables can be set on the container in which the daemon runs).


@dvdksn are you able to have a look? Or perhaps @jojoob is interested is interested in contributing changes?
