### ISSUE TITLE
Command to install docker-composer-plugin does not work under WSL 2

### ISSUE THREAD

**Issue by thiagodp** [docker/docs#18274]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Command to install docker-composer-plugin does not work under WSL 2:
```bash
sudo apt-get update
sudo apt-get install docker-compose-plugin
```
Output:

```bash
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:2 https://deb.nodesource.com/node_14.x focal InRelease [4583 B]
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Fetched 4583 B in 2s (2805 B/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package docker-compose-plugin
```

### Location

https://docs.docker.com/compose/install/linux/

**Comment by aevesdocker** [comment]
Hi @thiagodp, the Compose plugin is only available for Linux. If you want to use Compose on Windows, the easiest way is to install Docker Desktop, which includes Docker Compose

**Comment by thiagodp** [comment]
Thank you, @aevesdocker, I've installed it manually. 

Maybe the documentation could indicate that the package is not available on WSL.

**Comment by thaJeztah** [comment]
👋 if you're installing on Ubuntu in wsl2, this should work, but from the output you provided, it looks like you didn't configure your apt repository settings to include docker's package repository (download.docker.com), and because of that `apt-get-install` tried to find the package in Ubuntu's package repositories.

So, you probably missed the first step at https://docs.docker.com/compose/install/linux/#install-using-the-repository

<img width="567" alt="Screenshot 2023-09-28 at 13 49 42" src="https://github.com/docker/docs/assets/1804568/50c46385-f566-4ec6-8471-3dd9207657ed">

For Ubuntu, you can refer to this page to configure apt to include docker's package repository; https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

After the repository is configured, you should be able to continue with step 2 (the steps you posted in this ticket)

**Comment by thiagodp** [comment]
Thank you @thaJeztah.

In order to simplify the first step, I suggest to put its commands in a public `.sh` file that can be downloaded with `curl` and then executed. Thus, we can run a single-line command such as:
```bash
sh -c "$(curl -fsSL https://raw.githubusercontent.com/docker/docker/master/tools/install.sh)"
```

**Comment by thiagodp** [comment]
Oh, you already have such script [here](https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script). 😅
