### ISSUE TITLE
Wrong VERSION_CODE variable when add apt source

### ISSUE THREAD

**Issue by aiemkhanh** [docker/docs#18511]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Run command: . /etc/os-release && echo "$VERSION_CODENAME" on Ubuntu 22.04 => output: jammy
Expect output: bookworm
Output should be Debian code, not Ubuntu code because download repo is using Debian code for apt-get 

### Location

https://docs.docker.com/engine/install/debian/

### Suggestion

Instead using . /etc/os-release && echo "$VERSION_CODENAME" , we can use :  lsb_release -cs

**Comment by thaJeztah** [comment]
It looks like you're trying to use the installation instructions for _debian_ but you're running _ubuntu_.

Ubuntu has its own packages / repository on download.docker.com; refer to the Ubuntu installation documentation instead; https://docs.docker.com/engine/install/ubuntu/

Closing this issue, because of the above, but feel free to continue the conversation.
