### ISSUE TITLE
Unclear what names are legal in "AS name"

### ISSUE THREAD

**Issue by SRNissen** [docker/docs#19167]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

# The problem

    [FROM](https://docs.docker.com/engine/reference/builder/#from) [--platform=<platform>] <image> [AS <name>]

It is not clear what a legal `<name>` is.

# What I've tried

- In `https://docs.docker.com/engine/reference/builder/#from`
  - Ctrl-F "name" reveals 79 uses of "name" and none of them indicate what's legal
- In `https://docs.docker.com/glossary/`
  - Ctrl-F "name" reveals 21 uses of "name" and none of them indicate what's legal
- In `https://docs.docker.com/compose/compose-file/04-version-and-name/`:
  - Ctrl-F "name" reveals 15 uses of "name" and none of them indicate what's legal

There is a section

    https://docs.docker.com/build/building/multi-stage/#name-your-build-stages

very specifically about naming stages but it *also* does not specify what a legal name is.

### Location

https://docs.docker.com/build

### Suggestion

**Either:**

Specify in docs what stage names are supported

**Or:**

Commit to never making any update to docker that change stage name parsing, such that any name that accidentally works today will continue to work into the future.

**Comment by polarathene** [comment]
ASCII should be valid? Is the concern with using UTF-8 for language a user is comfortable in? Should be fairly easy to verify if that's supported?

Are you wanting an [ABNF](https://en.wikipedia.org/wiki/Augmented_Backus%E2%80%93Naur_form) definition?

**Comment by SRNissen** [comment]
> Are you wanting an [ABNF](https://en.wikipedia.org/wiki/Augmented_Backus%E2%80%93Naur_form) definition?

I am looking for any written-down description that docker has endorsed, such that I can write dockerfiles today and trust they will also build tomorrow.

> Should be fairly easy to verify if that's supported?

I feel like once I've

- searched through all the documentation on docker.com,
- read through the OCI papers, *and*
- googled enough to find out that containers-wg also can't find an answer,

I have reached a point where I can say "easy to verify" is not an accurate description of the state of the documentation.

**Comment by polarathene** [comment]
> such that I can write dockerfiles today and trust they will also build tomorrow.

How unlikely is that to happen if you use a name that is ASCII? It's not like the software itself will cease to work, if you have a version of Docker to build it will continue to work fine.

With respect to semver, that could potentially become incompatible in the future, but that's kind of the point 🤷‍♂️ 

---

> I have reached a point where I can say "easy to verify" is not an accurate description of the state of the documentation.

It's easy to verify that you can build with whatever input you're concerned about? Or are you just throwing theoretical concerns?

A bit more context would probably be helpful, the best I could assume is you're wanting to build something that takes untrusted inputs from third-parties and you're trying to define some bounds? But then if ASCII was sufficient, there wouldn't really be an issue there either?

---

Anyway... perhaps you're not comfortable with browsing code, that's ok. I gave it a quick look (never looked into this source before) and found it fairly easy.

One caveat is this is the source of what you'd have build your `Dockerfile` typically, which since Docker v23 is BuildKit. There is of course a variety of other software that Docker / Moby has no influence over which may do things differently. Perhaps there is a spec somewhere, these aren't concerns I have and if you're not writing your own software to parse/build images from a `Dockerfile`, then that's not likely to be relevant to you either.

For BuildKit we can quickly [find this](https://github.com/moby/buildkit/blob/36863a0ff7eac0af1d21a1b40b534aa3ce03fa19/frontend/dockerfile/instructions/commands.go#L485-L503):

```go
// Stage represents a bundled collection of commands.
//
// Each stage begins with a FROM command (which is consumed into the Stage),
// indicating the source or stage to derive from, and ends either at the
// end-of-the file, or the start of the next stage.
//
// Stages can be named, and can be additionally configured to use a specific
// platform, in the case of a multi-arch base image.
type Stage struct {
	Name     string    // name of the stage
	Commands []Command // commands contained within the stage
	BaseName string    // name of the base stage or source
	Platform string    // platform of base source to use

	Comment string // doc-comment directly above the stage

	SourceCode string         // contents of the defining FROM command
	Location   []parser.Range // location of the defining FROM command
}
```

No surprises there, a `string` type. We can look a bit further, the `Stage.Name` is probably parsed somewhere into a `string` right? 🤔 

[Here we go](https://github.com/moby/buildkit/blob/36863a0ff7eac0af1d21a1b40b534aa3ce03fa19/frontend/dockerfile/instructions/parse.go#L347-L384):

```go
func parseFrom(req parseRequest) (*Stage, error) {
	stageName, err := parseBuildStageName(req.args)

// ...

func parseBuildStageName(args []string) (stageName string, err error) {
	switch {
	case len(args) == 3 && strings.EqualFold(args[1], "as"):
		stageName = strings.ToLower(args[2])
		if !validStageName.MatchString(stageName) {
			return "", errors.Errorf("invalid name for build stage: %q, name can't start with a number or contain symbols", args[2])

// ...

var validStageName = regexp.MustCompile("^[a-z][a-z0-9-_.]*$")
```

So how about that, case insensitive (at least for this check) stage name that must start with `a-z` (no number or symbols), but afterwards you can have numbers and the symbols `-_.`.

[Here's a playground example](https://go.dev/play/p/P1g6mSlNpLt) (_my first Go program haha_). You can play around with that to verify but it should be fairly self-explanatory with those examples on what is permitted and what is not.

<details>
<summary>Source (if the playground link ever goes bad)</summary>

```go
package main

import (
	"fmt"
	"regexp"
	"strings"
)

var validStageName = regexp.MustCompile("^[a-z][a-z0-9-_.]*$")

func main() {
	examples := []string{"hello", "World", "Hello,World", "Hello-_.World", "Hello世界"}
	for _, s := range examples {
		if validStageName.MatchString(strings.ToLower(s)) {
			fmt.Printf("%s is valid\n", s)
		} else {
			fmt.Printf("%s is invalid\n", s)
		}
	}
}
```

</details>

Although, if you'd rather ignore the Go code, you could probably just play with [this interactive regex online utility](https://regex101.com) (_[Go regex reference](https://go-language.org/go-docs/regexp/)_). Here's a breakdown of the regex:

![image](https://github.com/docker/docs/assets/5098581/81a95cfa-d2a4-4470-9c4c-31c387739c3b)

---

Hopefully that's insightful for you and answers your question, at least for anything building an image via BuildKit (_which is what is appropriate for Docker and it's CLI_).

**Comment by polarathene** [comment]
> such that I can write dockerfiles today and trust they will also build tomorrow.

Apart from version pinning your software (_or rollback if the stage name parsing did change in a breaking manner for you_), you may also be interested in [this](https://docs.docker.com/engine/reference/builder/#syntax) which should help ensure builders like BuildKit would (ideally) remain compatible (or inform you otherwise) when you request the specific Dockerfile syntax to build with:

```Dockerfile
# syntax=docker/dockerfile:1
```

The 1 does have point releases which could be used for being a bit more explicit about the minimum range. Newer instructions or changes to existing instructions required that as opt-in previously at least. [Here's an example](https://docs.docker.com/engine/reference/builder/#copy---parents):

> ![image](https://github.com/docker/docs/assets/5098581/2105ab9f-927e-429f-8d82-b0f79cecc048)

**Comment by SRNissen** [comment]
I did not know about the "syntax" directive and I am very happy to learn about it.

> How unlikely is that to happen if you use a name that is ASCII

That depends on the docker project's attitude to change management.

> theoretical concerns ... perhaps you're not comfortable with browsing code ... if you're not writing your own software to parse/build images from a Dockerfile, then that's not likely to be relevant to you either

...I think perhaps you and I work in very different fields.

I am afraid that I'm coming off as ungrateful and I want you to know:  I appreciate that you took the time to look in the code.

Unfortunately for me - unless buildkit has committed to never updating that code, "that's what the code said in January" is not an answer I can write in compliance docs, explain to my regulators, or recommend as a method to my juniors.

There is a correct way to write a Dockerfile. I want mine written that way. I would love it if Docker could tell me what it is. Possibly multiple ways, with SemVer.

There are also ways to write a Dockerfile that "happen to work." I want zero of *those* files in my repos.

Or... am I wrong here? Am I simply mistaken in thinking that there is a correct way to write Dockerfiles? Is it *all* just "happens to work" and it's been "happening to work" for so long that people have come to depend on it?

Either way, I'll try and dig deeper into the `syntax` directive, see if anybody wrote down what the specs are for version x.y.z.

**Comment by dvdksn** [comment]
Thanks @polarathene for chipping in, your input is always very appreciated and well-structured.

@SRNissen, as you've concluded, you can use the syntax directive to pin the Dockerfile frontend to a specific version. The syntax directive version is an image reference, so if you want to make sure your assumptions about the syntax never break, you can pin the frontend to a particular version with a digest. Or you can even create your own Dockerfile frontend version with whatever restrictions on multi-stage naming that you want to enforce.

For more information, see:

- https://docs.docker.com/build/dockerfile/frontend/
- https://docs.docker.com/develop/develop-images/guidelines/#pin-base-image-versions
