### ISSUE TITLE
Missing containerd.io apt packages

### ISSUE THREAD

**Issue by akerl** [docker/docs#19273]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

It looks like https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/ is missing the latest several containerd.io releases compared to https://github.com/containerd/containerd/releases . This is especially noteworthy because v1.7.13 containers the remediation for CVE-2024-21626.

Is there an alternative location that I should be looking for containerd.io apt packages?

### Location

https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/

**Comment by dvdksn** [comment]
Hi, thanks for raising the issue!

The standard distribution of engine v25.0.2 uses [containerd 1.6.28](https://github.com/containerd/containerd/releases/tag/v1.6.28) which also includes a fix for https://github.com/advisories/GHSA-xr7r-f8xq-vfvv.

[containerd.io_1.6.28-1_amd64.deb](https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/containerd.io_1.6.28-1_amd64.deb)
`2024-02-01 03:44:20 28.2 MiB`

If you're installing the static binary version, the packages are distributed here: https://download.docker.com/linux/static/stable/

The statuc binary version of v25.0.2 does include containerd v1.7.13

@thaJeztah please confirm or correct me here

**Comment by thaJeztah** [comment]
Ah, yes, correct; the static binaries come with containerd 1.7, but for the `deb` and `rpm` packages we currently ship containerd 1.6.x, which is their LTS release.

For the static packages, containerd and the docker engine are bundled together (so current versions of the engine can use current versions of containerd), but for `deb` and `rpm` installations, containerd is packaged separately; as those packages are shared between all versions of the engine (say, installing an older version of the docker engine would by default still install the "latest" version of the `containerd.io` package), we decided at the time to stick with the LTS release of containerd, because the docker engine itself did not need new features provided by containerd 1.7 (and up).

We're currently evaluating this (also after discussing support cycle for 1.7 - making sure that it doesn't reach EOL before 1.6), and we may switch to containerd 1.7 (or containerd 2.0) for those packages at some point.


Let me close this ticket, but feel free to continue the conversation!
