### ISSUE TITLE
Password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by ink-ru** [docker/docs#19839]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

To run the endpoints without an error, DB role creation needed. See an [issue](https://github.com/sameersbn/docker-postgresql/issues/112) for more info.

### Location

https://docs.docker.com/language/python/develop/

### Suggestion

Add text:
Get container
`docker ps`

Enter inside of the container
`docker exec -it <hash> bash`

Start query console
`psql`

Define password
ALTER ROLE postgres WITH PASSWORD 'mysecretpassword';

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.

The password should be specified in the `db/password.txt` file before running `docker compose up`.

If you skip creating the `password.txt` file and first run `docker compose up`, you'll initialize the database without your password and get this error.
Creating the `password.txt` file after running `docker compose up` won't fix the issue because the database has already been initialized. To fix the issue, you'll need to either manually specify the password as you've mentioned, or delete the volume and run docker compose up after `password.txt` has been created.

Skipping the password.txt step has been a common issue in many of the language guides. We need to rework that section.

**Comment by berkesayin** [comment]
Thanks for the detailed explanation. @craig-osterhout 

I think, it's not practical to delete volumes and run `docker compose up` command again. 

In my case, modifying the `db` service `environments` to adjust the PostgreSQL container's authentication method also worked and solved the auth error. 

- Issue: #19865 
- PR: #19866 

```yaml
environment:
  - POSTGRES_DB=example
  - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
  - POSTGRES_HOST_AUTH_METHOD=md5 #added 
  - PGDATA=/var/lib/postgresql/data/pgdata #added 
```
I wanted to share because this worked for me. Thanks.
