### ISSUE TITLE
Add Docker sock chmod

### ISSUE THREAD

**Issue by synergiator** [docker/docs#20411]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

For post installation steps, I have to use this command every time (last time on Debian):

sudo chmod 666 /var/run/docker.sock

otherwise I get an error:

permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.46/containers/json": dial unix /var/run/docker.sock: connect: permission denied

fix source: 

https://stackoverflow.com/questions/48957195/how-to-fix-docker-got-permission-denied-issue

Please include this post-installation step!

### Location

https://docs.docker.com/engine/install/linux-postinstall/

### Suggestion

add, at least for dev enivronment:

sudo chmod 666 /var/run/docker.sock

**Comment by thaJeztah** [comment]
Permissions on the socket are intentionally restricted; granting access to the socket is equivalent to `root` access on the host; see the documentation linked from the page you linked; https://docs.docker.com/engine/security/#docker-daemon-attack-surface

I'll close this ticket as this is intentional, but feel free to continue the conversation.
