### ISSUE TITLE
Antivirus software and Docker

### ISSUE THREAD

**Issue by asmigar** [docker/docs#20836]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

I presume you meant to `include` instead of ~~exclude~~

If you do choose to ~~exclude~~ include Docker's data directory from background virus scanning, you may want to schedule a recurring task that stops Docker, scans the data directory, and restarts Docker.

### Location

https://docs.docker.com/engine/security/antivirus/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. 

I think it's correct as-is because it refers to the event and not the list. You exclude it from background virus scanning. You include it on the exclusion list.
If switching include/exclude, it needs to refer to the list instead of the event.

For example:
`If you do choose to include Docker's data directory on the exclusion list, you may want to schedule a recurring task that stops Docker, scans the data directory, and restarts Docker.`

A more wordy example:
`If you do choose to include Docker's data directory on the exclusion list and therefore exclude it from background virus scanning, you may want to schedule a recurring task that stops Docker, scans the data directory, and restarts Docker.`

**Comment by g24annabellek** [comment]
If you do choose to include Docker's data directory on the exclusion list and therefore exclude it from background virus scanning, you may want to schedule a recurring task that stops Docker, scans the data directory, and restarts Docker.
