### ISSUE TITLE
User vs Developer

### ISSUE THREAD

**Issue by applexpert** [docker/docs#21168]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

Documentation is for developers, not end user's.  I am not a developer/programmer, but wish to install and use Docker on macOS.  No where does it explain how to create a container, install and configure images developed by others.  I am looking to run Home Assistant and a Web server.  I found the docs to be very confusing for a newbe.  Lastly, many terms are not defined, and way too much is assumed by the tech writer.

### Location

https://docs.docker.com/get-started/introduction/get-docker-desktop/

**Comment by dvdksn** [comment]
Thank you for your feedback. Our primary audience is developers using Docker to build, ship, and run applications. But we would love for our documentation to be accessible to anyone interested in using Docker.

Since you mentioned you want to learn more about the fundamentals, maybe you'd be interested in checking out the Docker basics concept series, here: https://docs.docker.com/get-started/docker-concepts/the-basics/what-is-a-container/

**Comment by usha-mandya** [comment]
@applexpert Please see to the Docker concepts section referenced above to learn the basics of Docker. I'm closing this issue. Feel free to add a comment if you have any other questions.
