### ISSUE TITLE
Java language guide Dockerfile issue on final stage

### ISSUE THREAD

**Issue by rogeriofrsouza** [docker/docs#21498]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

I have a Spring Boot REST API project and I followed the [Java language specific guide](https://docs.docker.com/guides/java/) instructions to containerize it in the right way.

However, the build stage [presented in the Dockerfile](https://docs.docker.com/guides/java/containerize/) makes my app raise an exception because it has no permission to create a file. This occurs because I use Logback FileAppender feature for logging.

```dockerfile
# Create a non-privileged user that the app will run under.
# See https://docs.docker.com/go/dockerfile-user-best-practices/
ARG UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    appuser
USER appuser
```

![Image](https://github.com/user-attachments/assets/a7fbf9b6-0376-4486-b6a2-2b942c397288)

### Location

https://docs.docker.com/guides/java/containerize/

### Suggestion

I know that logging to a file is not a standard for every Spring Boot application, and maybe, I should not do it. However, I wonder if the Docker build should be compatible with this because some projects may require some kind of access to the file system.

**Comment by dvdksn** [comment]
@ajeetraina @falconcr do you think it might be worth having a section about logging in this guide?

**Comment by falconcr** [comment]
I understand the concern, but my recommendation is to follow modern best practices for logging in containerized environments:

1. **Use `stdout` and `stderr` for logs:** This is the industry standard for containerized applications. It simplifies log collection and analysis with observability systems.

2. **Volumes for specific cases:** If your application strictly requires access to the filesystem, consider mounting an external volume to store log files.

3. **Redirect logs to external systems:** Configure Logback to send logs to a centralized logging solution (e.g., Elastic Stack or CloudWatch) rather than writing to local files.

Granting write permissions to the container’s filesystem is not recommended due to security concerns. Allowing the container to modify its own directories could create exploitable vulnerabilities. I suggest reviewing how your project could adopt these modern practices, aligned with Docker security principles.

CC @dvdksn @rogeriofrsouza

**Comment by rogeriofrsouza** [comment]
@falconcr thanks for these recommendations.

The project budget and logs output is rather low, seems like using a centralized logging stack isn't viable at the moment.
I tried to configure the Docker Compose volume but had the same permission error, could you recommend some configuration?

**Comment by dvdksn** [comment]
@rogeriofrsouza try `chown`ing the directory that you want to save your logs in to the container user

```
RUN mkdir /var/log/myapp && chown appuser /var/log/myapp
```
