### ISSUE TITLE
Missing information about windowsfilter storage driver

### ISSUE THREAD

**Issue by michha** [docker/docs#21602]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Neither https://docs.docker.com/engine/storage/drivers/ nor https://docs.docker.com/engine/storage/drivers/select-storage-driver/ mention the _windowsfilter_ driver or its options.

### Location

https://docs.docker.com/engine/storage/drivers/select-storage-driver/

### Suggestion

Please document _windowsfilter_ options like `dm.basesize`.

**Comment by dvdksn** [comment]
Looking into this. It seems like only `size` is supported, for setting the defaultSandboxSize (and it's documented [here](https://docs.docker.com/reference/cli/dockerd/#windowsfilter-options)).

You mention `dm.basesize` but that's for the (deprecated) devicemapper driver.

@thaJeztah I noticed in the description for the `size` opt that we say it defaults to 20GB. But the source code seems to suggest otherwise:

https://github.com/moby/moby/blob/0e8013d72da15077eb203869760e1d8cbfa46832/daemon/graphdriver/windows/windows.go#L44-L48

Should the default in fact be 127GB?
