### ISSUE TITLE
Deprecate overlay driver

### ISSUE THREAD

**Issue by bermudezmt** [docker/docs#7439]
### Problem description

Relates to [#7433](https://github.com/docker/docker.github.io/pull/7433) @thaJeztah: Thinking we should start deprecating the overlay driver; IIRC, with the Red Hat kernels now supporting overlay2, every supported distro that supports overlay now also supports overlay2, and I cannot think of any reason to use overlay instead of overlay2 for those.

### Problem location

- Future updates: storage/storagedriver/index.md

**Comment by kolyshkin** [comment]
For RHEL
* `overlay` (but not overlay2) is supported by RHEL 7.1 and 7.2.
* `overlay2` is supported since RHEL 7.3.
Meaning that if we deprecate overlay we deprecate RHEL/CentOS < 7.3

**Comment by andrewhsu** [comment]
This looks like a good idea to me. cc @mataneja

**Comment by mataneja** [comment]
RHEL/CentOS < 7.3 are already deprecated. Is there some other OS variant that supports _overlay_ that we still support?

**Comment by thaJeztah** [comment]
No, this would only be for older debian versions (which we dropped in 18.09).

RHEL, and thus RHEL < 7.3 was only built for Docker EE, which never had `overlay` in the list of supported storage drivers (it "worked" but was not supported).

**Comment by mataneja** [comment]
Is there a place where we called out `overlay` support that now needs to be cleaned up? As in, what does deprecation of `overlay` actually require?

**Comment by thaJeztah** [comment]
Deprecation means we'll remove it in a future release. We may want to add a "deprecated" warning at the top of the overlay storage driver page (describing that if your system supports overlay, it most likely supports overlay2, and has all the advantages, and none of the negatives of overlay)

**Comment by thaJeztah** [comment]
Main reason for deprecating things is to give people notice, and a chance to prepare for the feature to be removed. That was also the reason for the introduction of the feature deprecation policy; 
https://docs.docker.com/engine/#feature-deprecation-policy (although that originates from the open source maintainers, well before there even was CE/EE)

**Comment by mataneja** [comment]
@thaJeztah I understand the need for deprecation and am fully supportive of this. I am just curious what steps we need to take in order to accomplish this. From your comments above, it seems that it may simply be a warning on the overlay storage driver page? Can you plz link to it here? Also, is that the extent of the work?

**Comment by thaJeztah** [comment]
@mataneja From a documentation perspective; yes, I would make sure to;

- Add a deprecation warning on https://github.com/docker/docker.github.io/blob/master/storage/storagedriver/overlayfs-driver.md . There's already a "recomendation" to use `overlay2` instead of `overlay`, so I think that section should be rephrased a bit, and turned into a deprecation warning.
- In a follow up; think about removing the sections that are explaining how the legacy "overlay" driver works (there's a lot of detail about how it uses hardlinks, which is all irrelevant for overlay2)
- Update the "select a storage driver" page; https://github.com/docker/docker.github.io/blob/master/storage/storagedriver/select-storage-driver.md
  - I was already working on a PR to update this page a bit, because it really is outdated, and there are some really bad recomendations in there (such as calling out "vfs" a _recommended_ driver, which it definitely is not)

I would also recommend (if we do a patch release) to include these changes:

- https://github.com/docker/engine/pull/85 [18.09 backport] deprecate legacy "overlay", and "devicemapper" storage drivers
- https://github.com/docker/engine/pull/90 [18.09 backport] Skip deprecated storage-drivers in auto-selection

Those changes will;

- Add a warning to the output of `docker info` that notifies the user that they're using a deprecated storage driver
- Skip overlay (and devicemapper) when performing automatic selection of storage-drivers on a fresh install
  - the storage driver can still be used, and _will_ still be used on existing installations (so when upgrading an older engine) but won't be used _automatically_ on a fresh install

**Comment by ahh-docker** [comment]
@thaJeztah @mataneja I'll take care of this. Do you mind reviewing it when I'm done?

**Comment by ahh-docker** [comment]
Waiting for @mataneja, @mark-church, and @andrewhsu to review.

**Comment by thaJeztah** [comment]
.

**Comment by dvdksn** [comment]
The overlay driver was completely removed from docs in #17375
