### ISSUE TITLE
The Linux installation instructions need a little proofreading

### ISSUE THREAD

**Issue by Chloe-H** [docker/docs#7486]
File: [compose/install.md](https://docs.docker.com/compose/install/)
The Linux installation instructions link to the release page on GitHub and recommend getting installation instructions from there, then say that the step-by-step instructions are included below. However, there is a warning below the installation instructions that strongly urges the reader to go to the release page. This already seems strange, since the claim was that the instructions from the release page were merely duplicated on the install page, but whatever. Interestingly, the release page links back to the install page, which means we have a circular reference _and_ a confusing warning.

**Comment by Chloe-H** [comment]
Added bonus: the "Alternative Install Options" link doesn't work!

**Comment by paigehargrave** [comment]
@chris-crone Hi Chris - Would you mind taking a look at this? Thank you in advance!

**Comment by chris-crone** [comment]
@ulyssessouza has started looking at this.

**Comment by ulyssessouza** [comment]
@Chloe-H About having 2 pages on the installation, that's the release page is inserted in a broader context.
Since the docs page has more options, I think that makes sense to have a link in the github releases page to it. And from the docs page to the github one, be cause that's where the source is, in the case of more experienced users that for example, are looking for release candidate versions that are not documented in the first.

About the "Alternative Install Options" link, that's true that it doesn't work as it's brother located in the tab with the others.
