### ISSUE TITLE
Change Dockerfile

### ISSUE THREAD

**Issue by andrebianchessi** [docker/docs#9497]
File: [compose/django.md](https://docs.docker.com/compose/django/)

File:

```Dockerfile
FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/
```

Is redundant and has some useless lines (such as the WORKDIR line).
I recomend changing it to:

```Dockerfile
FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
COPY . /code/
RUN pip install -r requirements.txt
```

**Comment by thaJeztah** [comment]
Thanks for your suggestions, but there's some steps in that Dockerfile that are actually _on purpose_

Let me first mention the `WORKDIR`; I think the `WORKDIR` is good to have in that Dockerfile, but you're right that it's currently not taken advantage of. After setting the `WORKDIR`, other steps can be slightly simplified, and use `.` (current directory)` instead of `/code/`, so:

```Dockerfile
FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir -p /code
WORKDIR /code/
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
```

In the above;

```
RUN mkdir -p /code
```

- I changed `mkdir` to `mkdir -p`, which is usually recommended, so that it will only create the directory if it doesn't exist
- Even though `WORKDIR /code/` would create the directory as well, it would always create it as `root`, which may be problematic if the container runs as a different user, so because of that, it's good to manually create the directory first (using `mkdir` as mentioned above)
- I changed `/code/` to `.` in the `COPY` steps (because the current workdir is now `/code/`.

Next; the steps that you recommended removing;

```Dockerfile
COPY requirements.txt /code/
RUN pip install -r requirements.txt
```

Those steps may _look_ redundant, but actually serve a purpose, and is a common pattern to use for installing dependencies;

When building an image from a Dockerfile, docker uses a caching mechanism (the "build cache"). That cache is there to speed up re-building the image, and allows docker to skip steps that don't need updating (which can save a lot of time, as well as disk-space).

For `COPY`, Docker checks if the cache is still valid, based on the files that are added in the `COPY` step. If the cache is no longer valid, both the cache for the `COPY` step itself, and **every `RUN`, `COPY`, and `ADD` step following it** is invalidated, and will be run again.

The `COPY requirements.txt /code/` step is there so that the `pip install -r requirements.txt` is _only_ run if the requirements change (thus if the `requirements.txt` file itself is modified). Given that fetching dependencies can take a while, this can be a big time-saver when re-building the image.

Changing it to just 

```Dockerfile
COPY . /code/
RUN pip install -r requirements.txt
```

Would cause _any_ file change in your project to "bust" the cache, and to re-run the `pip install` again, even if the changes you made in the code do not affect the `requirements.txt` (and thus would not have needed the `pip install` to be run again).


It might be worth describing that in that document though (source file is in this repository; https://github.com/docker/docker.github.io/blob/master/compose/django.md), and the changes to the `WORKDIR` I mentioned above could be added to that document;

Are you perhaps interested in opening a pull request for one (or both) of those changes?

**Comment by JakeRowsell89** [comment]
@thaJeztah Since the original poster doesn't seemed to have actioned this, I've put in a PR to add parts of your answer. Please let me know if this is off the mark:
https://github.com/docker/docker.github.io/pull/9636

**Comment by deronnax** [comment]
you don't need the `RUN mkdir /code` because WORKDIR will create the directory if it doesn't exist (that's said in the Dockerfile reference)

**Comment by thaJeztah** [comment]
@deronnax see my comment earlier;

> Even though `WORKDIR /code/` would create the directory as well, it would always create it as `root`, which may be problematic if the container runs as a different user, so because of that, it's good to manually create the directory first (using mkdir as mentioned above)

**Comment by craig-osterhout** [comment]
Closing as the content is no longer contained in the docs.
